import {useRef,useState} from 'react';
import type {Analysis,Inputs,Position,Progress,TileRecord} from './core/types';
import {destination,inverse} from './core/geo';
import {exportCSV,exportJSON,importJSON} from './core/export';
import {validateInputs} from './core/engine';
import {BrowserCache} from './data/cache';
import {MapView} from './components/Map';
import {ProfileChart} from './components/Charts';
import './style.css';
export const DEFAULTS:Inputs={observer:{lat:48.14,lon:11.58},observerHeight:1.6,azimuth:90,distance:10000,step:1,model:'dgm1',domMode:'critical',date:new Date().toISOString().slice(0,10),timezone:'Europe/Berlin',atmosphere:{k:0.13,solarRefraction:true,pressure:1010,temperature:10},mode:'los',azimuthStep:0.1,fanHalfWidth:4,proxy:'',groundOffset:0,positionUncertainty:0};
function NumberField({label,value,onChange,min,max,step=0.01}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;step?:number}){return <label>{label}<input type="number" value={Number.isNaN(value)?'':value} step={step} min={min} max={max} onChange={e=>onChange(e.target.value===''?NaN:Number(e.target.value))}/></label>;}
export function App(){
  const [inputs,setInputs]=useState<Inputs>(DEFAULTS),[result,setResult]=useState<Analysis>(),[progress,setProgress]=useState<Progress>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tiles,setTiles]=useState<TileRecord[]>([]),[select,setSelect]=useState<'observer'|'target'>('observer'),[theme,setTheme]=useState('light');
  const worker=useRef<Worker|null>(null);
  const set=<K extends keyof Inputs>(key:K,value:Inputs[K])=>{setInputs(i=>({...i,[key]:value}));setResult(undefined);};
  const point=(p:Position,kind:'observer'|'target')=>{if(busy)return;if(kind==='observer')set('observer',p);else{const v=inverse(inputs.observer,p);setInputs(i=>({...i,azimuth:v.azimuth,distance:Math.round(v.distance)}));setResult(undefined);}};
  const start=()=>{
    try{validateInputs(inputs);}catch(e){setError((e as Error).message);return;}
    worker.current?.terminate();const w=new Worker(new URL('./analysis.worker.ts',import.meta.url),{type:'module'});worker.current=w;
    setBusy(true);setError('');setResult(undefined);setTiles([]);setProgress({stage:'Start',fraction:0,detail:'Analyse wird vorbereitet'});
    w.onmessage=e=>{const d=e.data;if(d.type==='progress'){setProgress(d.progress);if(d.progress.tile)setTiles(old=>[...old.filter(t=>!(t.id===d.progress.tile.id&&t.model===d.progress.tile.model)),d.progress.tile]);}if(d.type==='result'){setResult(d.result);setBusy(false);w.terminate();}if(d.type==='error'){setError(d.message);setBusy(false);w.terminate();}};
    w.onerror=()=>{setError('Analyseprozess unerwartet beendet. Weniger Entfernung oder gröbere Abtastung versuchen.');setBusy(false);w.terminate();};w.postMessage({inputs});
  };
  const upload=async(files:FileList|null)=>{
    if(!files)return;setBusy(true);setError('');
    try{for(const file of files){setNotice(`Importiere ${file.name}`);await new Promise<void>((resolve,reject)=>{const w=new Worker(new URL('./analysis.worker.ts',import.meta.url),{type:'module'});worker.current=w;w.onmessage=e=>{w.terminate();if(e.data.type==='error')reject(new Error(e.data.message));else{setTiles(t=>[...t.filter(x=>x.id!==e.data.metadata.id||x.model!==e.data.metadata.model),e.data.metadata]);resolve();}};w.onerror=()=>{w.terminate();reject(new Error('GeoTIFF-Import fehlgeschlagen'));};w.postMessage({file,model:inputs.model});});}setNotice('GeoTIFF importiert. Lokale Herkunft ist nicht unabhängig verifiziert.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  };
  const download=(text:string,name:string,type:string)=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const time=(iso?:string)=>iso?new Intl.DateTimeFormat('de-DE',{timeZone:inputs.timezone,hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(iso)):'—';
  const endpoint=destination(inputs.observer,Number.isFinite(inputs.azimuth)?inputs.azimuth:90,Number.isFinite(inputs.distance)?inputs.distance:10000);
  const b=result?.profile.blocker,sb=result?.profile.surfaceBlocker;
  const shownTiles=result?.tiles??tiles;
  return <div className={`app ${theme}`}><a href="#results" className="skip">Zu den Ergebnissen</a><header className="topbar"><a className="brand" href="./"><span className="brand-mark">◒</span><span>Horizon<span className="brand-sub">SUNRISE ANALYZER</span></span></a><div className="top-meta"><span>BAYERN · DGM1 / DOM20</span><span className="version">0.8 · Forschungsstand</span><button onClick={()=>setTheme(t=>t==='light'?'dark':'light')} aria-label="Farbschema wechseln">◐</button><a href="https://github.com/gtowncity/horizon-sunrise-analyzer" target="_blank" rel="noreferrer">Dokumentation ↗</a></div></header>
  <div className="workspace"><aside className="sidebar"><div className="side-heading"><span className="eyebrow">ANALYSE EINRICHTEN</span><h1>Den Horizont berechnen.</h1></div><div className="mode-switch" role="group" aria-label="Analysemodus"><button aria-pressed={inputs.mode==='los'} disabled={busy} onClick={()=>set('mode','los')}>Sichtlinie</button><button aria-pressed={inputs.mode==='sunrise'} disabled={busy} onClick={()=>set('mode','sunrise')}>Sonnenaufgang</button></div>
  <fieldset disabled={busy}><legend><span>01</span> Beobachter</legend><div className="pair"><NumberField label="Breite ° N" value={inputs.observer.lat} onChange={lat=>set('observer',{...inputs.observer,lat})} step={0.00001}/><NumberField label="Länge ° E" value={inputs.observer.lon} onChange={lon=>set('observer',{...inputs.observer,lon})} step={0.00001}/></div><NumberField label="Sichthöhe über Boden · m" value={inputs.observerHeight} min={0.05} max={100} onChange={v=>set('observerHeight',v)}/><div className="small-actions"><button onClick={()=>{navigator.clipboard.writeText(`${inputs.observer.lat}, ${inputs.observer.lon}`).then(()=>setNotice('Koordinate kopiert.'),()=>setError('Zwischenablage nicht verfügbar.'));}}>Koordinate kopieren</button><button onClick={()=>{setInputs(DEFAULTS);setResult(undefined);}}>Zurücksetzen</button></div></fieldset>
  <fieldset disabled={busy}><legend><span>02</span> {inputs.mode==='los'?'Sichtlinie':'Sonnentag'}</legend>{inputs.mode==='los'?<><NumberField label="Azimut · ° von Nord" value={inputs.azimuth} min={0} max={360} onChange={v=>set('azimuth',v)}/><details><summary>Zielkoordinate eingeben</summary><NumberField label="Zielbreite ° N" value={Number(endpoint.lat.toFixed(5))} onChange={lat=>point({...endpoint,lat},'target')}/><NumberField label="Ziellänge ° E" value={Number(endpoint.lon.toFixed(5))} onChange={lon=>point({...endpoint,lon},'target')}/></details></>:<><label>Datum<input type="date" min="1901-01-01" max="2099-12-31" value={inputs.date} onChange={e=>set('date',e.target.value)}/></label><label>Zeitzone<select value={inputs.timezone} onChange={e=>set('timezone',e.target.value)}><option>Europe/Berlin</option><option>UTC</option></select></label><p className="hint">Standardhorizont und erster sichtbarer Sonnenrand werden getrennt berechnet.</p></>}<NumberField label="Maximale Entfernung · km" value={inputs.distance/1000} min={0.01} max={80} step={0.1} onChange={v=>set('distance',v*1000)}/></fieldset>
  <fieldset disabled={busy}><legend><span>03</span> Höhenmodell</legend><label>Datengrundlage<select value={inputs.model} onChange={e=>set('model',e.target.value as Inputs['model'])}><option value="dgm1">DGM1 · Gelände ohne Objekte</option><option value="dom20">DOM20 + DGM1 · Oberfläche</option></select></label>{inputs.model==='dom20'&&<label>DOM-Abdeckung<select value={inputs.domMode} onChange={e=>set('domMode',e.target.value as Inputs['domMode'])}><option value="critical">Kandidatenregionen · unvollständig</option><option value="full">Gesamte Sichtlinien · datenintensiv</option></select></label>}<p className="hint">Amtliche GeoTIFFs werden automatisch über den bayerischen ZIP-Dienst geladen und lokal zwischengespeichert.</p><details><summary>Lokale Dateien & Cache</summary><label>GeoTIFF für gewähltes Modell<input type="file" accept=".tif,.tiff" multiple onChange={e=>void upload(e.target.files)}/></label><button onClick={()=>new BrowserCache().clear().then(()=>{setNotice('Höhendaten-Cache gelöscht.');setTiles([]);},()=>setError('Cache konnte nicht gelöscht werden.'))}>Cache löschen</button><label>Gespeicherte Analyse importieren<input type="file" accept=".json" onChange={async e=>{try{const file=e.target.files?.[0];if(file){const a=importJSON(await file.text());setInputs(a.inputs);setResult(a);setNotice('Importierter Analysebericht – Datenherkunft nicht erneut verifiziert.');}}catch(err){setError((err as Error).message);}}}/></label></details></fieldset>
  <fieldset disabled={busy}><details><summary>Atmosphäre & Genauigkeit</summary><NumberField label="Terrestrische Refraktion k · 0 = aus" value={inputs.atmosphere.k} min={0} max={0.5} onChange={v=>set('atmosphere',{...inputs.atmosphere,k:v})}/><label className="checkbox"><input type="checkbox" checked={inputs.atmosphere.solarRefraction} onChange={e=>set('atmosphere',{...inputs.atmosphere,solarRefraction:e.target.checked})}/>Astronomische Refraktion</label><div className="pair"><NumberField label="Druck · hPa" value={inputs.atmosphere.pressure} onChange={v=>set('atmosphere',{...inputs.atmosphere,pressure:v})}/><NumberField label="Temperatur · °C" value={inputs.atmosphere.temperature} onChange={v=>set('atmosphere',{...inputs.atmosphere,temperature:v})}/></div><NumberField label="Räumlicher Schritt · m" value={inputs.step} min={0.2} max={50} onChange={v=>set('step',v)}/>{inputs.mode==='sunrise'&&<><NumberField label="Azimutschritt · °" value={inputs.azimuthStep} min={0.01} max={1} onChange={v=>set('azimuthStep',v)}/><NumberField label="Halbe Fächerbreite · °" value={inputs.fanHalfWidth} min={1} max={15} onChange={v=>set('fanHalfWidth',v)}/></>}<NumberField label="Positionsunsicherheit · m" value={inputs.positionUncertainty} onChange={v=>set('positionUncertainty',v)}/><NumberField label="Künstliche Bodenerhöhung · m" value={inputs.groundOffset} min={0} max={500} onChange={v=>set('groundOffset',v)}/><p className="hint">k ist eine Modellannahme. Sonnenrefraktion hängt getrennt davon von Druck und Temperatur ab. Bodenerhöhung ist nur ein Sensitivitätstest.</p></details></fieldset>
  <div className="run-panel">{busy?<button className="run cancel" onClick={()=>{worker.current?.terminate();setBusy(false);setError('Analyse abgebrochen. Bereits geladene Kacheln bleiben im Cache.');}}>Analyse abbrechen</button>:<button className="run" onClick={start}>Analyse starten <span>→</span></button>}<p>Berechnung lokal in deinem Browser</p></div></aside>
  <main id="results"><div className="main-heading"><div><span className="eyebrow">{inputs.mode==='los'?'TERRAIN · LINE OF SIGHT':'SOLAR · FIRST VISIBLE'}</span><h2>{inputs.mode==='los'?'Sichtlinie & Horizont':'Sonne trifft Horizont'}</h2></div><span className="data-badge">{result?(result.tiles.some(t=>t.state==='Local')?'LOKALE DATEN':result.tiles.every(t=>t.state==='Cached')?'CACHED · AMTLICH':'REAL · AMTLICH'):'DATEN NICHT GELADEN'}</span></div>
  <section className="map-panel"><div className="map-toolbar"><div role="group" aria-label="Kartenklick setzt"><span>Klick setzt</span><button aria-pressed={select==='observer'} onClick={()=>setSelect('observer')}>Beobachter</button><button aria-pressed={select==='target'} onClick={()=>setSelect('target')}>Zielpunkt</button></div><span>{Number.isFinite(inputs.azimuth)?inputs.azimuth.toFixed(2):'—'}° · {(inputs.distance/1000).toFixed(2)} km</span></div>{Number.isFinite(inputs.observer.lat)&&Number.isFinite(inputs.observer.lon)&&<MapView inputs={inputs} result={result} onPoint={point} select={select}/>}</section>
  {busy&&progress&&<section className="progress-box" role="status" aria-live="polite"><strong>{progress.stage}</strong><span>{progress.detail}</span><progress max={1} value={progress.fraction}/><small>Große Korridore können mehrere Minuten und viele MB benötigen. Bereits geladene Kacheln werden wiederverwendet.</small></section>}
  {error&&<div role="alert" className="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}
  <section className="metrics"><article><span>TERRAIN-HORIZONT</span><strong>{b?`${b.angle>=0?'+':''}${b.angle.toFixed(3)}°`:'—'}</strong><small>{b?`${(b.distance/1000).toFixed(2)} km · ${b.terrain.toFixed(2)} m NHN`:'Maximaler scheinbarer Höhenwinkel'}</small></article><article><span>BEOBACHTERBODEN</span><strong>{result?`${result.profile.ground.toFixed(2)} m`:'—'}</strong><small>DHHN2016 · über Normalhöhennull</small></article><article><span>{inputs.mode==='sunrise'?'STANDARD-AUFGANG':'RELATIVE BLOCKERHÖHE'}</span><strong>{inputs.mode==='sunrise'?time(result?.standardSunrise):b&&result?`${(b.terrain-result.profile.ground).toFixed(1)} m`:'—'}</strong><small>{inputs.mode==='sunrise'?inputs.timezone:'Höhe über Beobachterboden'}</small></article><article className="accent"><span>{inputs.mode==='sunrise'?'ERSTER SONNENRAND':'SICHT ZUM ZIELBODEN'}</span><strong>{inputs.mode==='sunrise'?time(result?.contact?.time):result?(result.profile.targetVisible?'Frei':'Verdeckt'):'—'}</strong><small>{inputs.mode==='sunrise'?(inputs.model==='dom20'&&inputs.domMode==='critical'?'Nur Teilhorizont · vorläufig':'Modellzeit · Unsicherheit siehe unten'):'Innerhalb des abgetasteten Profils'}</small></article></section>
  {result?<><section className="panel"><div className="panel-heading"><div><span className="eyebrow">01 / PROFIL</span><h3>Gelände in der Sichtlinie</h3></div><span>{result.profile.samples.length.toLocaleString('de-DE')} Abtastpunkte</span></div><ProfileChart result={result} kind="height"/></section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">02 / WINKELSICHT</span><h3>Was bildet den Horizont?</h3></div><span>Lokale Horizontalebene = 0°</span></div><ProfileChart result={result} kind="angle"/></section>{result.horizon.length>0&&<section className="panel"><h3>Horizontfunktion H(A)</h3><ProfileChart result={result} kind="horizon"/></section>}{sb&&<section className="panel"><h3>Oberfläche über dem Gelände</h3><p>DOM-Horizont {sb.surfaceAngle?.toFixed(3)}° bei {(sb.distance/1000).toFixed(2)} km. DOM−DGM ist keine semantische Baumhöhe.</p><ProfileChart result={result} kind="excess"/></section>}
  <section className="panel uncertainty"><span className="eyebrow">03 / EINORDNUNG</span><h3>Modellgrenzen & Sensitivität</h3><ul>{result.warnings.map(w=><li key={w}>{w}</li>)}</ul>{result.sensitivity?.length!==0&&<p>Bei einer Horizontverschiebung von ±0,1° ändert sich die Kontaktzeit um {result.sensitivity?.map(s=>`${s.deltaSeconds?.toFixed(1)??'unbestimmt'} s`).join(' / ')}. Das ist eine Sensitivität, kein vollständiges Konfidenzintervall.</p>}<p>Wolken, Dunst, aktuelle Vegetation und außergewöhnliche atmosphärische Schichtung können die Beobachtung verändern.</p></section>
  <section className="panel"><div className="panel-heading"><h3>Reproduzierbare Ergebnisse</h3><div className="export-actions"><button onClick={()=>download(exportJSON(result),'horizon-analysis.json','application/json')}>JSON exportieren</button><button onClick={()=>download(exportCSV(result),'horizon-profile.csv','text/csv')}>CSV exportieren</button></div></div><details><summary>Scientific Debug · Daten & Parameter</summary><pre>{JSON.stringify({version:result.version,commit:result.commit,crs:'EPSG:25832',verticalDatum:'DHHN2016',samples:result.profile.samples.length,step:result.inputs.step,curvature:'GRS80 normal-section / effective radius',radius:result.profile.radius,atmosphere:result.inputs.atmosphere,ephemeris:'Astronomy Engine 2.1.19',contact:result.contact,elapsedMs:result.elapsedMs},null,2)}</pre></details><details><summary>Profilwerte als Tabelle (erste 200; vollständig im CSV)</summary><div className="table-scroll"><table><thead><tr><th>Distanz m</th><th>Breite</th><th>Länge</th><th>DGM m</th><th>DOM m</th><th>Winkel °</th></tr></thead><tbody>{result.profile.samples.slice(0,200).map(s=><tr key={s.distance}><td>{s.distance}</td><td>{s.lat.toFixed(6)}</td><td>{s.lon.toFixed(6)}</td><td>{s.terrain.toFixed(3)}</td><td>{s.surface?.toFixed(3)??'—'}</td><td>{s.distance?s.angle.toFixed(4):'—'}</td></tr>)}</tbody></table></div></details></section></>:<section className="empty panel"><span className="empty-icon">⌁</span><div><h3>Deine Sichtlinie beginnt hier.</h3><p>Setze Beobachter und Ziel auf der Karte oder gib die Koordinaten ein. Die Analyse lädt reale Höhendaten und zeigt den höchsten scheinbaren Winkel entlang der Sichtlinie.</p><p className="hint">Es werden keine Beispieldaten als Ergebnisse angezeigt.</p></div></section>}
  {shownTiles.length>0&&<section className="panel"><h3>Datenkacheln <span className="muted">{(shownTiles.reduce((s,t)=>s+t.bytes,0)/1048576).toFixed(1)} MB unkomprimierte Archivdateien</span></h3><div className="table-scroll"><table><thead><tr><th>Modell</th><th>Kachel</th><th>Status</th><th>MB</th><th>Abrufzeit</th></tr></thead><tbody>{shownTiles.map(t=><tr key={t.model+t.id}><td>{t.model.toUpperCase()}</td><td>{t.id}</td><td>{t.state}</td><td>{(t.bytes/1048576).toFixed(2)}</td><td>{t.downloadedAt?.slice(0,10)}</td></tr>)}</tbody></table></div></section>}
  <footer><p>Datenquelle: <a href="https://geodaten.bayern.de/opengeodata/">Bayerische Vermessungsverwaltung – www.geodaten.bayern.de</a> · <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Höhenprofile und Winkel sind abgeleitete Berechnungen.</p><p>Ephemeriden: Astronomy Engine · Karte: OpenStreetMap · Quellcode: MIT</p></footer></main></div></div>;
}
